### PR TITLE
Update extension tutorial with the DEX support.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`app/docs/modules/coreum-fungible-token/coreum-fungible-token.mdx` line 240 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe5oyV88wkQnMjClB6:-ODe5oyV88wkQnMjClB7:b-kb4s06) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/f95bf3db489204318b8c4bce3114ce2c9dcfc109/app/docs/modules/coreum-fungible-token/coreum-fungible-token.mdx#L240)):*
> ```MDX
> ### Extension
> Extension is a powerful feature which lets the admin override some functionalities of the token by attaching a smart contract to the token that can administrate it.
> The are two types of extensions: `ExtensionTransfer` and `ExtensionPlaceOrder`.
> ```

I think it causes more confusion if we say that there are two types of extension, because one extension can be both at the same time
___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 225 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7hcJ1RxtPt0Ii_t-:-ODe7hcJ1RxtPt0Ii_t0:b-yta0im) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L225)):*
> ```MDX
> 
> ### A simple bank transfer.
> _Checkout `extension/simple` branch to see code for this example._
> ```

Why this reference is deleted?
___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 297 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7pjDD5BNr-PelDMf:-ODe7pjDD5BNr-PelDMg:b-yta0im) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L297)):*
> ```MDX
> 
> ### Reject some transactions.
> _Checkout `extension/reject` branch to see code for this example._
> ```

Why this reference is deleted?
___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 535 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7utzC4wEFbcXlkIi:-ODe7utzC4wEFbcXlkIj:b-yta0im) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L535)):*
> ```MDX
> 
> ### Custom send commission rate.
> _Checkout `extension/send-commission-rate` branch to see code for this example._
> ```

Why this reference is deleted?
___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 652 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe82URA_ybkVRcbO4Z:-ODe82URA_ybkVRcbO4_:b-yta0im) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L652)):*
> ```MDX
> 
> ### Custom burn rate.
> _Checkout `extension/burn-rate` branch to see code for this example._
> ```

Why this reference is deleted?
___
*[`app/docs/overview/smart-tokens/smart-tokens.mdx` line 210 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe6UWAES03tPkzInPa:-ODe6UWAES03tPkzInPb:b-ya81ng) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/f95bf3db489204318b8c4bce3114ce2c9dcfc109/app/docs/overview/smart-tokens/smart-tokens.mdx#L210)):*
> ```MDX
> ### Extension
> Extension is a powerful feature which lets the admin override some functionalities of the token by attaching a smart contract to the token that can administrate it.
> The are two types of extensions: `ExtensionTransfer` and `ExtensionPlaceOrder`.
> ```

Same as above

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil)

___
*[`app/docs/tutorials/build-apps/amm/amm.mdx` line 56 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODeBgrx9kF230l5DVWa:-ODeBgry8sIm00bKIedg:b-7amhsp) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/build-apps/amm/amm.mdx#L56)):*
> ```MDX
> RES=$(cored tx wasm store artifacts/astroport_token.wasm \
>     --from wallet --gas auto --gas-adjustment 1.3 -y -b block --output json $COREUM_NODE_ARGS $COREUM_CHAIN_ID_ARGS)
> CODE_ID_TOKEN=$(echo $RES | jq -r '.logs[0].events[-1].attributes[-1].value')
> ```

what is changed to justify this change ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)* status: all files reviewed, 7 unresolved discussions (waiting on @masihyeganeh and @miladz68)

___
*[`app/docs/modules/coreum-fungible-token/coreum-fungible-token.mdx` line 240 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe5oyV88wkQnMjClB6:-ODeDzlfATRiLvFibKUf:b-8ezbo2) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/f95bf3db489204318b8c4bce3114ce2c9dcfc109/app/docs/modules/coreum-fungible-token/coreum-fungible-token.mdx#L240)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I think it causes more confusion if we say that there are two types of extension, because one extension can be both at the same time
</blockquote></details>

Agree, updated.
___
*[`app/docs/overview/smart-tokens/smart-tokens.mdx` line 210 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe6UWAES03tPkzInPa:-ODeE0lb3zTBz3VpJsXU:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/f95bf3db489204318b8c4bce3114ce2c9dcfc109/app/docs/overview/smart-tokens/smart-tokens.mdx#L210)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Updated.
___
*[`app/docs/tutorials/build-apps/amm/amm.mdx` line 56 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODeBgrx9kF230l5DVWa:-ODeE3dFChCeRICt_XX1:bwfycrm) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/build-apps/amm/amm.mdx#L56)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

what is changed to justify this change ?
</blockquote></details>

WASM order of the event attributes.
___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 225 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7hcJ1RxtPt0Ii_t-:-ODeED9KCg1DDgxE_Ogm:b37bjox) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L225)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Why this reference is deleted?
</blockquote></details>

All references are deleted sice the code copied completely in the tutorial (and tested). We don't need to support multiple branches with simple code.
___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 297 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7pjDD5BNr-PelDMf:-ODeEYy4Dfnu5NkfCw2O:b-y6w8re) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L297)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Why this reference is deleted?
</blockquote></details>

Replied in prev thread.
___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 535 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7utzC4wEFbcXlkIi:-ODeEVXcE4DmJnhb9QH0:b-y6w8re) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L535)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Why this reference is deleted?
</blockquote></details>

Replied in prev thread.
___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 652 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe82URA_ybkVRcbO4Z:-ODeEYUc8ZYiddkNZfTe:b-y6w8re) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L652)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Why this reference is deleted?
</blockquote></details>

Replied in prev thread.

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 225 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7hcJ1RxtPt0Ii_t-:-ODefHPkATcepQyz7aNF:b2m2lyv) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L225)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

All references are deleted sice the code copied completely in the tutorial (and tested). We don't need to support multiple branches with simple code.
</blockquote></details>

The point of that other repo is to simply clone and checkout different branches to have a code that fully works and has all the needed dependencies there, so they don't need to put pieces of puzzle together

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @masihyeganeh and @miladz68)

___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 225 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7hcJ1RxtPt0Ii_t-:-ODeqjkAAV_kuFlso8Qx:bors7ed) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L225)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

The point of that other repo is to simply clone and checkout different branches to have a code that fully works and has all the needed dependencies there, so they don't need to put pieces of puzzle together
</blockquote></details>

IMO the code is so simple, so you can just copy it to the initial template.

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68)

___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 225 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7hcJ1RxtPt0Ii_t-:-ODexKZ2EQDneGAVmtvQ:b-dytb3a) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L225)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO the code is so simple, so you can just copy it to the initial template.
</blockquote></details>

I insist on having the easiest way for users to integrate our features. But if it is hard to maintain, we can decide not to do that. @miladz68 WDYT?

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)* status: all files reviewed, 4 unresolved discussions (waiting on @masihyeganeh)

___
*[`app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx` line 225 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/86#-ODe7hcJ1RxtPt0Ii_t-:-ODf996T74mC1BfjizbW:bhjawoz) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/0db0f739401d9e419524f9feac9e87db7f7ec0c7/app/docs/tutorials/use-tokens/asset-ft-extension/asset-ft-extension.mdx#L225)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I insist on having the easiest way for users to integrate our features. But if it is hard to maintain, we can decide not to do that. @miladz68 WDYT?
</blockquote></details>

removing this link makes the other repo obsolete, Although it is simple, but still for someone who is completely fresh it will take some time to put this into the template. It is worth keeping the other repo since it is already done. let's discuss in a call to reach final agreement.

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/86)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
