### PR TITLE
Add DEX module docs and CLI tutorial.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/88)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/88)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzLZJ_9WU6_GZedD1u:-ODzLZJ_9WU6_GZedD1v:b-oez1yd) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L23)):*
> ```MDX
>     * `sell` - means that the order is to sell `base_denom` `quantity` with the `price`.
>     * `buy` - means that the order is to buy `base_denom` `quantity` with the `price`.
> * `time_in_force` - how long an order will remain active before it is executed or expires, based on matching state.
> ```

I suggest to write a different description than `good_til`. It is confusing
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 50 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzMxLU3ZXcvUnAJDcZ:-ODzMxLU3ZXcvUnAJDc_:bdhozmc) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L50)):*
> ```MDX
> each order book. The `price_tick` mostly depends on the price of the assets traded, that's why we can define the
> variable for a token used to define the order book `price_tick`. This variable is named `unified_ref_amount`.
> `unified_ref_amount`for token represents the amount of the token subunit you need to pay to buy 1 USD dollar. If the
> ```

Needs a space after `unified_ref_amount`
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzNV6nDwCzaIjipeWp:-ODzNV6oC9HjZcHi-g-w:b-mmjiwh) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L58)):*
> ```MDX
> 
> ```
> price_tick(base_denom/quote_denom) = 10^(floor(log10((unified_ref_amount(quote_denom) / unified_ref_amount(base_denom)))) + price_tick_exponent)
> ```

I'm suggesting to use LaTeX or any other libs to show these lines or any other math notations better

Also, by replacing the values from your example in this equation, I can't get the expected result:

```
price_tick(base_denom/quote_denom) = 10^(floor(log10((unified_ref_amount(quote_denom) / unified_ref_amount(base_denom)))) + price_tick_exponent)

= 10^(floor(log10((10000.0 / 10000.0))) + -8)

= -14
```
Let me know what I'm missing (Just let's think I'm someone not familiar with this and reading the doc)
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 111 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzQKYUA3bbimE8Khfb:-ODzQKYUA3bbimE8Khfc:bo6cl73) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L111)):*
> ```MDX
> ### Time in force
> 
> The `time_in_force` setting specifies the execution conditions of an order, dictating how long it should remain active
> ```

Again, it's better to have a different description than the Good til
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 138 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzQ_OLC8oY9KYrwFI9:-ODzQ_OLC8oY9KYrwFIA:bn9nrrs) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L138)):*
> ```MDX
> deposit that ensures users have a vested interest in their orders, helping to prevent spam and malicious activities.
> Once the order is executed that reserve is released.
> The default reserve amount is  `10 CORE` and can be updated by the governance.
> ```

unnecessary extra space before `10 CORE`
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 171 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzR8Ac5lbzYBY8FKUY:-ODzR8AdCkEP_xFwvokn:b-z7gxpf) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L171)):*
> ```MDX
> admin to cancel the user's orders, the `dex_order_cancellation` feature must be enabled.
> 
> ### Restricted trade
> ```

Is it a title which should have two pound signs or the text is missing?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/88)* status: all files reviewed, 6 unresolved discussions (waiting on @masihyeganeh and @miladz68)

___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzLZJ_9WU6_GZedD1u:-ODzV0-f8taPVcRxd_26:b-i714jn) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L23)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I suggest to write a different description than `good_til`. It is confusing
</blockquote></details>

What is wrong here?
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 50 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzMxLU3ZXcvUnAJDcZ:-ODzV6R30PVtPvvwnpCF:b-896fix) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L50)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Needs a space after `unified_ref_amount`
</blockquote></details>

Done.
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzNV6nDwCzaIjipeWp:-ODzVddk8kQFY575Bdgy:bk4b5lb) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L58)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I'm suggesting to use LaTeX or any other libs to show these lines or any other math notations better

Also, by replacing the values from your example in this equation, I can't get the expected result:

```
price_tick(base_denom/quote_denom) = 10^(floor(log10((unified_ref_amount(quote_denom) / unified_ref_amount(base_denom)))) + price_tick_exponent)

= 10^(floor(log10((10000.0 / 10000.0))) + -8)

= -14
```
Let me know what I'm missing (Just let's think I'm someone not familiar with this and reading the doc)
</blockquote></details>

How did you get ```-14``` ? 

```
10^(floor(log10((10000.0 / 10000.0))) + -8) = 10^-8
``` 

However I've updated the results in the table since it was computed based on -5 default `price_tick_exponent`, but we changed it to `-8` recently.

What is regarding `LaTeX`, not sure that it's required for such a simple formula. 
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 111 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzQKYUA3bbimE8Khfb:-ODz_v3H9y-GnpTGfL4G:bmx1hmz) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L111)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Again, it's better to have a different description than the Good til
</blockquote></details>

Which is better? Suggest, please.
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 138 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzQ_OLC8oY9KYrwFI9:-ODza6wa8CLzx4jYOXTu:b-8ezbo2) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L138)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

unnecessary extra space before `10 CORE`
</blockquote></details>

Agree, updated.
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 171 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzR8Ac5lbzYBY8FKUY:-ODzaTFA0ycdVNjXoA4V:b-l7lgg5) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L171)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Is it a title which should have two pound signs or the text is missing?
</blockquote></details>

You are right, we need to remove it, it was the old name.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/88)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzLZJ_9WU6_GZedD1u:-ODzcLsEAaU0P3hsTFFB:b-9tpezb) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L23)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is wrong here?
</blockquote></details>

Sorry, missed the ending of the sentences
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzNV6nDwCzaIjipeWp:-ODzcX5r6P5kihkRl72J:bjkb1jp) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How did you get ```-14``` ? 

```
10^(floor(log10((10000.0 / 10000.0))) + -8) = 10^-8
``` 

However I've updated the results in the table since it was computed based on -5 default `price_tick_exponent`, but we changed it to `-8` recently.

What is regarding `LaTeX`, not sure that it's required for such a simple formula.
</blockquote></details>


___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 111 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzQKYUA3bbimE8Khfb:-ODzceIADYY6CYTDcHRU:b-y5jljo) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L111)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Which is better? Suggest, please.
</blockquote></details>

Sorry, my bad. missed the ending of the sentences

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/88)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-ODzNV6nDwCzaIjipeWp:-ODzdQFy8b11qfMcGoBp:bvak0ax) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/99653d5d32e3fbebd202833b5eeb2a4d5a1c8b5a/app/docs/modules/coreum-dex/coreum-dex.mdx#L58)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>


</blockquote></details>

Ok, I'm wrong

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/88)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil)

___
*[`app/docs/tutorials/get-started/cli/coreum-dex-cli/page.tsx` line 12 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDt1rf1Jg2Tj1NKPuK:-OEDt1rf1Jg2Tj1NKPuL:b-34pddv) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/tutorials/get-started/cli/coreum-dex-cli/page.tsx#L12)):*
> ```XML
>     'Coreum CLI Guide',
>     'Transferring Funds Coreum',
>     'Staking Tokens Coreum',
> ```

I think staking is not related to this page.
___
*[`app/docs/modules/coreum-dex/page.tsx` line 14 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDsr4uCp39UtDEiGrm:-OEDsr4uCp39UtDEiGrn:b-ewf7cm) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/page.tsx#L14)):*
> ```XML
>     'Blockchain token creation',
>     'Assetft module',
>     'Minting tokens',
> ```

I think minting and burning is not related to this page.
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDuBIYB1sQ3gYaOJGr:-OEDuBIYB1sQ3gYaOJGs:b6dwrvs) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L19)):*
> ```MDX
> * `price` - value of one unit of the `base_denom` expressed in terms of the `quote_denom`. It indicates how much of the
>   `quote_denom` is needed to buy one unit of the `base_denom`.
> * `quantity` - is amount of the base `base_denom` being traded.
> ```

extra `base` word.
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDuIpVAEZFyKm7y8pr:-OEDuIpVAEZFyKm7y8ps:b-gdeh7n) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L21)):*
> ```MDX
> * `quantity` - is amount of the base `base_denom` being traded.
> * `side`
>     * `sell` - means that the order is to sell `base_denom` `quantity` with the `price`.
> ```

we should explain that if case of sell, the selling amount is tracked and used to calculate how much of order is filled, but in case of buy, the receive amount is tracked.
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDxp9u5fznWO8Uf6cq:-OEDxp9u5fznWO8Uf6cr:b-3sq6fk) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L39)):*
> ```MDX
> ### 2-way matching
> 
> Coreum DEX uses a 2-way matching system for processing all placed orders. This approach matches orders within its own
> ```

This is an implementation detail, to the outside world, there is only 1 orderbook. 
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDyWJY0Iw6XT3Y77Ak:-OEDyWJY0Iw6XT3Y77Al:b-qrcutu) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L50)):*
> ```MDX
> each order book. The `price_tick` mostly depends on the price of the assets traded, that's why we can define the
> variable for a token used to define the order book `price_tick`. This variable is named `unified_ref_amount`.
> `unified_ref_amount` for token represents the amount of the token subunit you need to pay to buy 1 USD dollar. If the
> ```

we should give instructions for issuers how to calculated unified ref amount for their tokens
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 68 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDzUVI0qiW2yaKSHpv:-OEDzUVI0qiW2yaKSHpw:b7yr7ah) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L68)):*
> ```MDX
> | unified_ref_amount(AAA) | unified_ref_amount(BBB) | price_tick(AAA/BBB) | price_tick(BBB/AAA) |
> |-------------------------|-------------------------|---------------------|---------------------|
> | 10000.0                 | 10000.0                 | 10^-5               | 10^-5               |
> ```

I guess you should update price tick to -8 in this table as well. I see -5 is used in first example. 
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 103 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEE-14cAeXyRkfVOr8d:-OEE-14cAeXyRkfVOr8e:b-9nwtux) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L103)):*
> ```MDX
> ### Balance locking/freezing/whitelisting/clawback.
> 
> When a user places an order we lock the coins in the assetft (similar to freezing), both assetft and native coins. Also,
> ```

mention of assetft and native coins add more confusion than information. 
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 107 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEE-G13Aq7Tg_39HALm:-OEE-G1416IEv3YepVQu:bcj4t5p) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L107)):*
> ```MDX
> At the time of the placement we enforce all assetft rules. If, at the time of matching, the assetft rules for the
> maker orders are changed, the orders will be still executed with the amounts in the order book. That's why to avoid
> unexpected behavior with the `freezing/whitelisting/clawback` the token admin should [cancel](#Order-cancellation) users
> ```

users orders -> user's orders
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 144 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEE-XgeCotWSeZw0SJD:-OEE-XgeCotWSeZw0SJE:b3lejcg) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L144)):*
> ```MDX
> 
> The number of active orders a user can have for each denom is limited by a value called `max_orders_per_denom`,
> which is determined by DEX governance.
> ```

current value should be mentioned. 
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 167 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEE02xX5MhJKTlrubiq:-OEE02xX5MhJKTlrubir:b-tnz2a8) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L167)):*
> ```MDX
> ### Order cancellation
> 
> The users can cancel their orders within the DEX. Or The token admin or gov can cancel user orders within the system.
> ```

mention that admin can cancel only when that feature is enabled. I see that it is mentioned at the end of paragraph, but they should be next to each other.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/88)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil)

___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDuIpVAEZFyKm7y8pr:-OEIMyQc3s1-pj9W3wtE:b-woahga) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Here we describe the same, but with the different words.
</blockquote></details>

I am not understanding that from this wording. 
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDxp9u5fznWO8Uf6cq:-OEIN8LM40L8rPCdz7fX:b9s2wi) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually - not. When you place an order you might think that if you place a base/quote order it will matched only against the base/quote order booksorders.
</blockquote></details>

to the outside world, there is only 1 order book.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/docs-next/88)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68)

___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDuIpVAEZFyKm7y8pr:-OEIhbRiDg7YUXOrsevr:b-f4p0ye) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L21)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am not understanding that from this wording.
</blockquote></details>

When you sell you want to spend, if you buy - receive. That's the basic logic.
___
*[`app/docs/modules/coreum-dex/coreum-dex.mdx` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/docs-next/88#-OEDxp9u5fznWO8Uf6cq:-OEIhvxA63U4ixGcrEFN:b-dlxu05) ([raw file](https://github.com/CoreumFoundation/docs-next/blob/34d0dd4704fcc22d517b8675e22a3d6de1a4f9b0/app/docs/modules/coreum-dex/coreum-dex.mdx#L39)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

to the outside world, there is only 1 order book.
</blockquote></details>

VIA CLI 2 order books.

**Pull request merged**
